### ISSUE TITLE
Monospaced font problem

### ISSUE THREAD

**Issue by F0x06** [AbeEstrada/atom-hex#10]
Hi, i have font-related issues (not monospaced), with the default Hex plugin, the hex view looks like this:

![default_font](https://cloud.githubusercontent.com/assets/7167311/4046248/9bcb0fc8-2d30-11e4-993d-deee2f81d2c9.png)

I fixed it by modifiyng stylesheets/hex.less, added a font-family value for header, .hex and .ascii, it looks like this now:

![monospaced_font](https://cloud.githubusercontent.com/assets/7167311/4046279/dc4313d4-2d30-11e4-8365-8f66452f25d9.png)

I used this font:

```javascript
font-family: "Courier New", Courier, "Lucida Sans Typewriter", "Lucida Typewriter", monospace;
```

Cheers,
F0x

**Comment by AbeEstrada** [comment]
The package uses the default monospace font, if you use a different font you have to change the style manually, I can't force all the users to use a monospaced font, they have the option to modify the file `styles.less`
