### ISSUE TITLE
Deprecated calls – please see #6278

### ISSUE THREAD

**Issue by clauseggers** [AbeEstrada/atom-hex#16]
Deprecated calls – please see #6278
https://github.com/atom/atom/issues/6278

**Comment by AbeEstrada** [comment]
Are you seeing any warnings related to this package?

I don't

![screenshot 2015-04-15 16 50 22](https://cloud.githubusercontent.com/assets/7937/7170915/9e969d1a-e38f-11e4-9a9d-84d428638a62.png)

**Comment by clauseggers** [comment]
No, it’s the same issue as described in #6278, meaning that the calls appear under the atom core. Disabling atom-hex clears those warnings. Please bear in mind that other packages also triggers this atom-core warning, so to test try only having atom-hex enabled and disabled.

**Comment by AbeEstrada** [comment]
@clauseggers thank you very much, I updated (https://github.com/AbeEstrada/atom-hex/commit/c1a5d9090fc29f0cc9db476ee7b1e20a4ff56f5f) the package and removed the deprecated APIs.

**Comment by clauseggers** [comment]
You’re welcome! Thanks for fixing it!
